<?php

// ENRICHED DOMAIN KEYWORDS - Copié depuis ImageContextService.php extractMainEntities()
return [
    'food' => [
        'food', 'nourriture', 'cuisine', 'gastronomie', 'culinaire', 'cooking',
        'restaurant', 'café', 'bar', 'bistro', 'brasserie', 'pizzeria',
        'chef', 'cuisinier', 'pâtissier', 'boulanger', 'sommelier',
        'recette', 'recipe', 'plat', 'menu', 'carte', 'spécialité',
        'ingrédients', 'produits', 'frais', 'local', 'terroir', 'bio',
        'viande', 'poisson', 'fruits de mer', 'seafood', 'sushi', 'sashimi',
        'légumes', 'vegetables', 'fruits', 'salad', 'soupe', 'entrée',
        'dessert', 'pâtisserie', 'gâteau', 'tarte', 'cookie', 'chocolat',
        'vin', 'wine', 'bière', 'beer', 'cocktail', 'boisson', 'drink',
        'breakfast', 'petit déjeuner', 'brunch', 'lunch', 'déjeuner', 'dinner', 'dîner',
        'street food', 'fast food', 'food truck', 'livraison', 'delivery',
        'végétarien', 'vegan', 'végétalien', 'sans gluten', 'gluten free',
        'épices', 'herbes', 'aromates', 'condiments', 'sauce',
        'boulang', 'viennoiserie', 'croissant', 'pain', 'traiteur', 'alimentation',
    ],

    'travel' => [
        'voyage', 'tourisme', 'vacances', 'séjour', 'escapade', 'weekend', 'circuit',
        'destination', 'île', 'plage', 'mer', 'océan', 'côte', 'littoral', 'baie',
        'madagascar', 'nosy be', 'sainte marie', 'antananarivo', 'tananarive', 'antsirabe',
        'tuléar', 'toliara', 'diego suarez', 'antsiranana', 'majunga', 'mahajanga',
        'fort dauphin', 'taolagnaro', 'morondava', 'avenue des baobabs', 'ifaty', 'anakao',
        'hotel', 'hôtel', 'resort', 'lodge', 'bungalow', 'villa', 'hébergement',
        'restaurant', 'gastronomie', 'cuisine locale', 'spécialités', 'plats typiques',
        'plongée', 'snorkeling', 'surf', 'kitesurf', 'kayak', 'bateau', 'croisière',
        'excursion', 'randonnée', 'trekking', 'aventure', 'exploration', 'safari',
        'parc national', 'réserve naturelle', 'faune', 'flore', 'biodiversité',
        'lémurien', 'lémuriens', 'baobab', 'baobabs', 'caméléon', 'tortue', 'baleine',
        'coucher de soleil', 'lever de soleil', 'panorama', 'paysage', 'nature',
        'tropical', 'exotique', 'paradisiaque', 'authentique', 'préservé', 'sauvage',
        'culture malgache', 'traditions', 'artisanat', 'vannerie', 'sculpture',
        'musique malgache', 'danse traditionnelle', 'festival', 'célébration',
        'vanille', 'épices', 'rhum', 'cacao', 'café', 'fruits tropicaux',
        'lagon', 'récif corallien', 'corail', 'poissons tropicaux', 'raie manta',
        'forêt tropicale', 'jungle', 'cascade', 'rivière', 'lac', 'montagne',
        'tour', 'agence de voyage', 'avion', 'camping', 'transport',
    ],

    'health' => [
        'santé', 'health', 'wellness', 'bien-être', 'forme', 'vitalité',
        'médecine', 'médical', 'docteur', 'médecin', 'infirmier', 'hôpital', 'clinique',
        'fitness', 'sport', 'exercice', 'entraînement', 'musculation', 'cardio',
        'yoga', 'méditation', 'relaxation', 'mindfulness', 'pleine conscience',
        'nutrition', 'alimentation', 'régime', 'diet', 'healthy food', 'superfoods',
        'vitamines', 'protéines', 'glucides', 'lipides', 'macro', 'micro-nutriments',
        'perte de poids', 'minceur', 'détox', 'jeûne', 'fasting',
        'sommeil', 'repos', 'récupération', 'fatigue', 'insomnie',
        'stress', 'anxiété', 'dépression', 'santé mentale', 'psychologie',
        'thérapie', 'coaching', 'développement personnel', 'confiance en soi',
        'massage', 'spa', 'soins', 'beauté', 'cosmétique', 'skincare',
        'pharmacie', 'médicaments', 'traitement', 'vaccin', 'prévention',
        'dentaire', 'optique', 'audition', 'physiothérapie', 'ostéopathie',
        'maladie', 'symptômes', 'diagnostic', 'guérison', 'rémission',
        'gym', 'kinésithérapeute', 'dentiste', 'soin',
    ],

    'education' => [
        'éducation', 'formation', 'apprentissage', 'learning', 'enseignement',
        'école', 'université', 'collège', 'lycée', 'académie', 'institut',
        'cours', 'leçon', 'tutorat', 'coaching', 'mentorat', 'mentoring',
        'e-learning', 'formation en ligne', 'mooc', 'webinaire', 'classe virtuelle',
        'diplôme', 'certification', 'qualification', 'compétences', 'skills',
        'étudiant', 'professeur', 'enseignant', 'formateur', 'instructeur',
        'pédagogie', 'méthode', 'programme', 'curriculum', 'syllabus',
        'examen', 'test', 'évaluation', 'note', 'résultats', 'performance',
        'recherche', 'étude', 'analyse', 'mémoire', 'thèse', 'doctorat',
        'bourse', 'scholarship', 'aide financière', 'prêt étudiant',
        'langues', 'language', 'anglais', 'français', 'espagnol', 'chinois',
        'mathématiques', 'sciences', 'histoire', 'géographie', 'littérature',
        'stage', 'tutoriel',
    ],

    'tech' => [
        'intelligence artificielle', 'ia', 'machine learning', 'deep learning', 'neural network',
        'blockchain', 'cryptocurrency', 'bitcoin', 'ethereum', 'nft', 'web3', 'metaverse',
        'cloud computing', 'aws', 'azure', 'google cloud', 'saas', 'paas', 'iaas',
        'applications', 'logiciels', 'plateformes', 'systèmes', 'données', 'big data',
        'cybersécurité', 'sécurité informatique', 'hacking', 'firewall', 'encryption',
        'programmation', 'développement', 'code', 'software', 'hardware', 'api', 'framework',
        'mobile', 'application mobile', 'ios', 'android', 'react native', 'flutter',
        'robotique', 'automation', 'iot', 'internet of things', '5g', '6g',
        'réalité virtuelle', 'vr', 'réalité augmentée', 'ar', 'mixed reality',
        'quantum computing', 'edge computing', 'serverless', 'microservices', 'devops',
        'technologie', 'digital', 'informatique', 'logiciel', 'application', 'web',
        'innovation', 'startup tech', 'cloud', 'data', 'robotique',
    ],

    'marketing' => [
        'marketing', 'campagne', 'publicité', 'promotion', 'communication',
        'audience', 'engagement', 'conversion', 'leads', 'prospects', 'clients potentiels',
        'réseaux sociaux', 'social media', 'facebook', 'instagram', 'twitter', 'linkedin', 'tiktok',
        'contenu', 'content marketing', 'storytelling', 'copywriting', 'rédaction',
        'seo', 'référencement', 'google', 'search engine', 'keywords', 'backlinks',
        'sem', 'sea', 'google ads', 'facebook ads', 'publicité en ligne',
        'branding', 'marque', 'identité visuelle', 'logo', 'charte graphique',
        'influence', 'influenceur', 'ambassadeur', 'partenariat influenceur',
        'email marketing', 'newsletter', 'automation marketing', 'crm', 'marketing automation',
        'analytics', 'données', 'metrics', 'tracking', 'pixel', 'tag manager',
        'funnel', 'tunnel de conversion', 'landing page', 'call to action', 'cta',
        'communauté', 'community management', 'modération', 'engagement communauté',
        'viralité', 'buzz', 'tendance', 'hashtag', 'trending',
        'content', 'digital marketing',
    ],

    'finance' => [
        'stratégie', 'croissance', 'revenus', 'chiffre affaires', 'bénéfices', 'profits',
        'clients', 'marché', 'concurrence', 'compétitivité', 'part de marché',
        'investissement', 'financement', 'budget', 'performance', 'roi', 'kpi',
        'startup', 'entreprise', 'pme', 'corporation', 'scale-up', 'licorne', 'unicorn',
        'e-commerce', 'commerce électronique', 'marketplace', 'boutique en ligne',
        'fintech', 'healthtech', 'edtech', 'proptech', 'insurtech', 'regtech',
        'levée de fonds', 'venture capital', 'business angel', 'incubateur', 'accélérateur',
        'business model', 'business plan', 'pitch', 'valuation', 'exit strategy',
        'management', 'leadership', 'gouvernance', 'ressources humaines', 'recrutement',
        'négociation', 'partenariat', 'collaboration', 'alliance stratégique',
        'innovation', 'disruption', 'transformation digitale', 'pivot', 'scalabilité',
        'rentabilité', 'marge', 'trésorerie', 'cash flow', 'burn rate', 'runway',
        'comptabilité', 'audit', 'fiscalité', 'conformité', 'réglementation',
        'finance', 'banque', 'économie', 'argent', 'épargne', 'bourse', 'crypto',
        'assurance', 'crédit', 'prêt', 'conseiller financier', 'patrimoine',
    ],

    'fashion' => [
        'mode', 'fashion', 'style', 'tendance', 'trend', 'look',
        'vêtements', 'clothes', 'prêt-à-porter', 'haute couture', 'luxe',
        'accessoires', 'sac', 'chaussures', 'bijoux', 'jewelry', 'montres',
        'styliste', 'designer', 'créateur', 'collection', 'défilé', 'fashion week',
        'shopping', 'boutique', 'magasin', 'e-shop', 'online shopping',
        'vêtement', 'couture', 'textile', 'design de mode', 'maroquinerie',
        'accessoire', 'chaussure',
    ],

    'real_estate' => [
        'immobilier', 'real estate', 'propriété', 'property', 'maison', 'appartement',
        'villa', 'studio', 'loft', 'duplex', 'penthouse', 'résidence',
        'achat', 'vente', 'location', 'investissement immobilier',
        'architecture', 'construction', 'rénovation', 'travaux', 'aménagement',
        'design intérieur', 'décoration', 'mobilier', 'furniture', 'meuble',
        'jardin', 'terrasse', 'balcon', 'piscine', 'garage',
        'agent immobilier', 'agence', 'promoteur', 'notaire', 'hypothèque',
        'promotion immobilière',
    ],

    'beauty' => [
        'beauté', 'beauty', 'cosmétique', 'maquillage', 'makeup', 'skincare',
        'parfum', 'perfume', 'fragrance', 'cosmetics', 'soins',
        'coiffure', 'hair', 'coiffeur', 'salon', 'barbier', 'barber',
        'ongles', 'nails', 'manucure', 'pédicure', 'nail art',
        'esthétique', 'spa', 'soin de la peau',
    ],

    'automotive' => [
        'automobile', 'voiture', 'car', 'véhicule', 'auto', 'moto', 'motorcycle',
        'électrique', 'electric', 'hybrid', 'hybride', 'tesla', 'ev',
        'conduite', 'driving', 'permis', 'license', 'route', 'road',
        'garage', 'atelier', 'mécanique', 'réparation', 'entretien', 'maintenance',
        'transport', 'mobilité', 'déplacement', 'logistics', 'livraison',
        'avion', 'airplane', 'aéroport', 'vol', 'flight', 'aviation',
        'train', 'railway', 'métro', 'subway', 'bus', 'tramway',
        'concessionnaire', 'pièce', 'moteur',
    ],

    'art' => [
        'art', 'arts', 'culture', 'culturel', 'artistique', 'création',
        'peinture', 'sculpture', 'dessin', 'illustration', 'gravure',
        'photographie', 'photo', 'photographe', 'image', 'cliché',
        'musique', 'musicien', 'compositeur', 'chanteur', 'concert', 'festival',
        'danse', 'ballet', 'chorégraphie', 'spectacle', 'performance',
        'théâtre', 'comédie', 'drame', 'pièce', 'acteur', 'scène',
        'cinéma', 'film', 'movie', 'réalisateur', 'production', 'tournage',
        'littérature', 'livre', 'roman', 'poésie', 'écrivain', 'auteur',
        'musée', 'galerie', 'exposition', 'vernissage', 'collection',
        'design', 'décoration', 'intérieur', 'aménagement',
        'artisanat', 'craft', 'handmade', 'fait main', 'création artisanale',
        'patrimoine', 'monument', 'histoire', 'tradition', 'héritage',
        'artiste', 'œuvre', 'graphisme',
    ],

    'nature' => [
        'nature', 'environnement', 'écologie', 'biodiversité', 'écosystème',
        'développement durable', 'sustainability', 'green', 'vert', 'bio', 'écologique',
        'forêt', 'jungle', 'savane', 'désert', 'montagne', 'vallée', 'canyon',
        'océan', 'mer', 'lac', 'rivière', 'fleuve', 'cascade', 'chute eau',
        'faune', 'animaux', 'mammifères', 'oiseaux', 'reptiles', 'insectes', 'papillons',
        'flore', 'plantes', 'fleurs', 'arbres', 'végétation', 'jardin botanique',
        'conservation', 'protection', 'préservation', 'espèces menacées', 'endangered',
        'climat', 'changement climatique', 'réchauffement', 'météo', 'saisons',
        'énergie renouvelable', 'solaire', 'éolien', 'hydraulique', 'géothermie',
        'recyclage', 'compost', 'zéro déchet', 'économie circulaire', 'upcycling',
        'agriculture', 'permaculture', 'agroécologie', 'biologique', 'organique',
    ],

    'sports' => [
        'sport', 'sports', 'athlète', 'sportif', 'compétition', 'championnat',
        'football', 'soccer', 'basketball', 'tennis', 'volleyball', 'rugby',
        'natation', 'swimming', 'cyclisme', 'vélo', 'running', 'course', 'marathon',
        'fitness', 'gym', 'musculation', 'bodybuilding', 'crossfit', 'hiit',
        'yoga', 'pilates', 'stretching', 'souplesse', 'flexibilité',
        'entraînement', 'workout', 'training', 'coach', 'personal trainer',
        'performance', 'endurance', 'force', 'vitesse', 'agilité',
        'nutrition sportive', 'protéines', 'supplements', 'récupération',
        'équipement', 'matériel', 'vêtements sport', 'chaussures sport',
        'stade', 'terrain', 'piscine', 'salle de sport', 'club',
    ],

    'family' => [
        'famille', 'family', 'parents', 'enfants', 'children', 'kids',
        'bébé', 'baby', 'nouveau-né', 'newborn', 'grossesse', 'pregnancy',
        'parentalité', 'parenting', 'éducation enfants', 'puériculture',
        'jouets', 'toys', 'jeux', 'games', 'activités enfants',
        'école maternelle', 'crèche', 'garderie', 'nursery', 'daycare',
        'anniversaire', 'birthday', 'fête', 'party', 'célébration',
        'vêtements enfants', 'baby clothes', 'poussette',
    ],

    'business' => [
        'business', 'entreprise', 'stratégie', 'management', 'gestion', 'leadership',
        'productivité', 'croissance', 'startup', 'entrepreneuriat', 'consultant',
        'conseil', 'service', 'projet', 'revenus', 'chiffre affaires', 'bénéfices',
        'profits', 'clients', 'marché', 'concurrence', 'compétitivité', 'part de marché',
        'investissement', 'financement', 'budget', 'performance', 'roi', 'kpi',
        'pme', 'corporation', 'scale-up', 'licorne', 'unicorn',
        'e-commerce', 'commerce électronique', 'marketplace', 'boutique en ligne',
        'incubateur', 'accélérateur', 'business model', 'gouvernance',
        'ressources humaines', 'recrutement', 'négociation', 'partenariat',
        'collaboration', 'alliance stratégique', 'innovation', 'disruption',
        'transformation digitale', 'pivot', 'scalabilité',
    ],

    'home_tech' => [
        'domotique', 'smart home', 'maison connectée', 'home automation',
        'iot', 'connected devices', 'alexa', 'google home', 'assistant vocal',
        'sécurité', 'caméra', 'alarme', 'surveillance', 'security',
        'électroménager', 'appliances', 'cuisine équipée', 'high-tech',
    ],

    'entertainment' => [
        'divertissement', 'entertainment', 'loisirs', 'hobbies', 'passion',
        'gaming', 'jeux vidéo', 'video games', 'console', 'pc gaming', 'esport',
        'streaming', 'netflix', 'youtube', 'twitch', 'podcast',
        'lecture', 'reading', 'livre audio', 'audiobook', 'ebook',
        'collection', 'collectionneur', 'hobby', 'bricolage', 'diy',
        'jardinage', 'gardening', 'plantes', 'potager', 'permaculture',
        'photographie amateur', 'drone', 'gopro', 'vidéo', 'vlog',
    ],
];
